### ISSUE TITLE
Fix TypeError: Router.use() requires a middleware function but got a Object

### ISSUE THREAD

**Issue by x47base** [x47base/Template-Web-Server#1]
`
PS C:\Template-Web-Server> node .\main.js
C:\Template-Web-Server\node_modules\express\lib\router\index.js:469
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))  
      ^

TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Template-Web-Server\node_modules\express\lib\router\index.js:469:13)       
    at Function.<anonymous> (C:\Template-Web-Server\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Template-Web-Server\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Template-Web-Server\main.js:26:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.14.2
`

**Comment by x47base** [comment]
Fixed, removed old code.
